//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator2009.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator2009.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string _Attention {
            get {
                return ResourceManager.GetString("_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Web Application ?.
        /// </summary>
        internal static string _Web_Application_ {
            get {
                return ResourceManager.GetString("_Web_Application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Completed Successfully.
        /// </summary>
        internal static string Activation_Completed_Successfully {
            get {
                return ResourceManager.GetString("Activation_Completed_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Completed Unsuccessfully: .
        /// </summary>
        internal static string Activation_Completed_Unsuccessfully {
            get {
                return ResourceManager.GetString("Activation_Completed_Unsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to activate the Translator on the .
        /// </summary>
        internal static string Are_you_sure_you_want_to_activate_the_Translator {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_activate_the_Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate the Translator from the .
        /// </summary>
        internal static string Are_you_sure_you_want_to_deactivate_the_Translator {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_deactivate_the_Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot quit application during activation/desactivation.
        /// </summary>
        internal static string Cannot_quit_application {
            get {
                return ResourceManager.GetString("Cannot_quit_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation Completed Successfully.
        /// </summary>
        internal static string Deactivation_Completed_Successfully {
            get {
                return ResourceManager.GetString("Deactivation_Completed_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation Completed Unsuccessfully .
        /// </summary>
        internal static string Deactivation_Completed_Unsuccessfully {
            get {
                return ResourceManager.GetString("Deactivation_Completed_Unsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the activation?.
        /// </summary>
        internal static string Do_you_want_to_cancel_the_activation {
            get {
                return ResourceManager.GetString("Do_you_want_to_cancel_the_activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the deactivation?.
        /// </summary>
        internal static string Do_you_want_to_cancel_the_deactivation {
            get {
                return ResourceManager.GetString("Do_you_want_to_cancel_the_deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  : Please verify the url and permissions: you need to use a Farm Admin Account.
        /// </summary>
        internal static string Please_verify_the_url_and_permissions_you_need_to_use_a_Farm_Admin_Account {
            get {
                return ResourceManager.GetString("Please_verify_the_url_and_permissions_you_need_to_use_a_Farm_Admin_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary file you entered does not exist.
        /// </summary>
        internal static string The_dictionary_file_you_entered_does_not_exist {
            get {
                return ResourceManager.GetString("The_dictionary_file_you_entered_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access .
        /// </summary>
        internal static string Unable_to_access_ {
            get {
                return ResourceManager.GetString("Unable_to_access_", resourceCulture);
            }
        }
    }
}
