//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LWQueue", Namespace="http://www.languageweaver.com/lwq")]
public partial class LWQueue : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback browseJobsOperationCompleted;
    
    private System.Threading.SendOrPostCallback cancelJobOperationCompleted;
    
    private System.Threading.SendOrPostCallback changeJobPrioOperationCompleted;
    
    private System.Threading.SendOrPostCallback createJobOperationCompleted;
    
    private System.Threading.SendOrPostCallback translateStringOperationCompleted;
    
    private System.Threading.SendOrPostCallback getJobStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback getServerInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTServerInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback readJobOperationCompleted;
    
    private System.Threading.SendOrPostCallback readJobDIMEOperationCompleted;
    
    private System.Threading.SendOrPostCallback rescanOperationCompleted;
    
    private System.Threading.SendOrPostCallback removeJobOperationCompleted;
    
    private System.Threading.SendOrPostCallback removeJobRangeOperationCompleted;
    
    private System.Threading.SendOrPostCallback removeJobRangeFilteredOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadDictionaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback downloadDictionaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback downloadDictionaryDIMEOperationCompleted;
    
    private System.Threading.SendOrPostCallback removeDictionaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadCustomizerOperationCompleted;
    
    private System.Threading.SendOrPostCallback downloadCustomizerOperationCompleted;
    
    private System.Threading.SendOrPostCallback downloadCustomizerDIMEOperationCompleted;
    
    private System.Threading.SendOrPostCallback removeCustomizerOperationCompleted;
    
    /// <remarks/>
    public LWQueue() {
        this.Url = "http://localhost:4640";
    }
    
    /// <remarks/>
    public event browseJobsCompletedEventHandler browseJobsCompleted;
    
    /// <remarks/>
    public event cancelJobCompletedEventHandler cancelJobCompleted;
    
    /// <remarks/>
    public event changeJobPrioCompletedEventHandler changeJobPrioCompleted;
    
    /// <remarks/>
    public event createJobCompletedEventHandler createJobCompleted;
    
    /// <remarks/>
    public event translateStringCompletedEventHandler translateStringCompleted;
    
    /// <remarks/>
    public event getJobStatusCompletedEventHandler getJobStatusCompleted;
    
    /// <remarks/>
    public event getServerInfoCompletedEventHandler getServerInfoCompleted;
    
    /// <remarks/>
    public event getTServerInfoCompletedEventHandler getTServerInfoCompleted;
    
    /// <remarks/>
    public event readJobCompletedEventHandler readJobCompleted;
    
    /// <remarks/>
    public event readJobDIMECompletedEventHandler readJobDIMECompleted;
    
    /// <remarks/>
    public event rescanCompletedEventHandler rescanCompleted;
    
    /// <remarks/>
    public event removeJobCompletedEventHandler removeJobCompleted;
    
    /// <remarks/>
    public event removeJobRangeCompletedEventHandler removeJobRangeCompleted;
    
    /// <remarks/>
    public event removeJobRangeFilteredCompletedEventHandler removeJobRangeFilteredCompleted;
    
    /// <remarks/>
    public event uploadDictionaryCompletedEventHandler uploadDictionaryCompleted;
    
    /// <remarks/>
    public event downloadDictionaryCompletedEventHandler downloadDictionaryCompleted;
    
    /// <remarks/>
    public event downloadDictionaryDIMECompletedEventHandler downloadDictionaryDIMECompleted;
    
    /// <remarks/>
    public event removeDictionaryCompletedEventHandler removeDictionaryCompleted;
    
    /// <remarks/>
    public event uploadCustomizerCompletedEventHandler uploadCustomizerCompleted;
    
    /// <remarks/>
    public event downloadCustomizerCompletedEventHandler downloadCustomizerCompleted;
    
    /// <remarks/>
    public event downloadCustomizerDIMECompletedEventHandler downloadCustomizerDIMECompleted;
    
    /// <remarks/>
    public event removeCustomizerCompletedEventHandler removeCustomizerCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#browseJobs", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("jobHeaders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("jobHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public JobHeader[] browseJobs([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int startAt, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int length, [System.Xml.Serialization.XmlElementAttribute("filterFlags", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] FilterFlag[] filterFlags, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
        object[] results = this.Invoke("browseJobs", new object[] {
                    startAt,
                    length,
                    filterFlags,
                    user});
        return ((JobHeader[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbrowseJobs(int startAt, int length, FilterFlag[] filterFlags, string user, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("browseJobs", new object[] {
                    startAt,
                    length,
                    filterFlags,
                    user}, callback, asyncState);
    }
    
    /// <remarks/>
    public JobHeader[] EndbrowseJobs(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((JobHeader[])(results[0]));
    }
    
    /// <remarks/>
    public void browseJobsAsync(int startAt, int length, FilterFlag[] filterFlags, string user) {
        this.browseJobsAsync(startAt, length, filterFlags, user, null);
    }
    
    /// <remarks/>
    public void browseJobsAsync(int startAt, int length, FilterFlag[] filterFlags, string user, object userState) {
        if ((this.browseJobsOperationCompleted == null)) {
            this.browseJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbrowseJobsOperationCompleted);
        }
        this.InvokeAsync("browseJobs", new object[] {
                    startAt,
                    length,
                    filterFlags,
                    user}, this.browseJobsOperationCompleted, userState);
    }
    
    private void OnbrowseJobsOperationCompleted(object arg) {
        if ((this.browseJobsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.browseJobsCompleted(this, new browseJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#cancelJob", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void cancelJob([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId) {
        this.Invoke("cancelJob", new object[] {
                    jobId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincancelJob(int jobId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("cancelJob", new object[] {
                    jobId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcancelJob(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void cancelJobAsync(int jobId) {
        this.cancelJobAsync(jobId, null);
    }
    
    /// <remarks/>
    public void cancelJobAsync(int jobId, object userState) {
        if ((this.cancelJobOperationCompleted == null)) {
            this.cancelJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelJobOperationCompleted);
        }
        this.InvokeAsync("cancelJob", new object[] {
                    jobId}, this.cancelJobOperationCompleted, userState);
    }
    
    private void OncancelJobOperationCompleted(object arg) {
        if ((this.cancelJobCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.cancelJobCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#changeJobPrio", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void changeJobPrio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int prio) {
        this.Invoke("changeJobPrio", new object[] {
                    jobId,
                    prio});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginchangeJobPrio(int jobId, int prio, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("changeJobPrio", new object[] {
                    jobId,
                    prio}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndchangeJobPrio(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void changeJobPrioAsync(int jobId, int prio) {
        this.changeJobPrioAsync(jobId, prio, null);
    }
    
    /// <remarks/>
    public void changeJobPrioAsync(int jobId, int prio, object userState) {
        if ((this.changeJobPrioOperationCompleted == null)) {
            this.changeJobPrioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeJobPrioOperationCompleted);
        }
        this.InvokeAsync("changeJobPrio", new object[] {
                    jobId,
                    prio}, this.changeJobPrioOperationCompleted, userState);
    }
    
    private void OnchangeJobPrioOperationCompleted(object arg) {
        if ((this.changeJobPrioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.changeJobPrioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#createJob", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("jobId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int createJob([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] JobParam jobParam, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] TranslationContext translationContext, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] text) {
        object[] results = this.Invoke("createJob", new object[] {
                    jobParam,
                    translationContext,
                    text});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateJob(JobParam jobParam, TranslationContext translationContext, byte[] text, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createJob", new object[] {
                    jobParam,
                    translationContext,
                    text}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndcreateJob(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void createJobAsync(JobParam jobParam, TranslationContext translationContext, byte[] text) {
        this.createJobAsync(jobParam, translationContext, text, null);
    }
    
    /// <remarks/>
    public void createJobAsync(JobParam jobParam, TranslationContext translationContext, byte[] text, object userState) {
        if ((this.createJobOperationCompleted == null)) {
            this.createJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateJobOperationCompleted);
        }
        this.InvokeAsync("createJob", new object[] {
                    jobParam,
                    translationContext,
                    text}, this.createJobOperationCompleted, userState);
    }
    
    private void OncreateJobOperationCompleted(object arg) {
        if ((this.createJobCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createJobCompleted(this, new createJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] translateString([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] JobParam jobParam, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] TranslationContext translationContext, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] text) {
        object[] results = this.Invoke("translateString", new object[] {
                    jobParam,
                    translationContext,
                    text});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegintranslateString(JobParam jobParam, TranslationContext translationContext, byte[] text, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("translateString", new object[] {
                    jobParam,
                    translationContext,
                    text}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndtranslateString(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void translateStringAsync(JobParam jobParam, TranslationContext translationContext, byte[] text) {
        this.translateStringAsync(jobParam, translationContext, text, null);
    }
    
    /// <remarks/>
    public void translateStringAsync(JobParam jobParam, TranslationContext translationContext, byte[] text, object userState) {
        if ((this.translateStringOperationCompleted == null)) {
            this.translateStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateStringOperationCompleted);
        }
        this.InvokeAsync("translateString", new object[] {
                    jobParam,
                    translationContext,
                    text}, this.translateStringOperationCompleted, userState);
    }
    
    private void OntranslateStringOperationCompleted(object arg) {
        if ((this.translateStringCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.translateStringCompleted(this, new translateStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#getJobStatus", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("jobHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public JobHeader getJobStatus([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId) {
        object[] results = this.Invoke("getJobStatus", new object[] {
                    jobId});
        return ((JobHeader)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetJobStatus(int jobId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getJobStatus", new object[] {
                    jobId}, callback, asyncState);
    }
    
    /// <remarks/>
    public JobHeader EndgetJobStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((JobHeader)(results[0]));
    }
    
    /// <remarks/>
    public void getJobStatusAsync(int jobId) {
        this.getJobStatusAsync(jobId, null);
    }
    
    /// <remarks/>
    public void getJobStatusAsync(int jobId, object userState) {
        if ((this.getJobStatusOperationCompleted == null)) {
            this.getJobStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJobStatusOperationCompleted);
        }
        this.InvokeAsync("getJobStatus", new object[] {
                    jobId}, this.getJobStatusOperationCompleted, userState);
    }
    
    private void OngetJobStatusOperationCompleted(object arg) {
        if ((this.getJobStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getJobStatusCompleted(this, new getJobStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#getServerInfo", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ServerInfo getServerInfo() {
        object[] results = this.Invoke("getServerInfo", new object[0]);
        return ((ServerInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetServerInfo(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getServerInfo", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ServerInfo EndgetServerInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ServerInfo)(results[0]));
    }
    
    /// <remarks/>
    public void getServerInfoAsync() {
        this.getServerInfoAsync(null);
    }
    
    /// <remarks/>
    public void getServerInfoAsync(object userState) {
        if ((this.getServerInfoOperationCompleted == null)) {
            this.getServerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServerInfoOperationCompleted);
        }
        this.InvokeAsync("getServerInfo", new object[0], this.getServerInfoOperationCompleted, userState);
    }
    
    private void OngetServerInfoOperationCompleted(object arg) {
        if ((this.getServerInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getServerInfoCompleted(this, new getServerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#getTServerInfo", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("tservers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public TServerInfo[] getTServerInfo() {
        object[] results = this.Invoke("getTServerInfo", new object[0]);
        return ((TServerInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTServerInfo(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTServerInfo", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public TServerInfo[] EndgetTServerInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TServerInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void getTServerInfoAsync() {
        this.getTServerInfoAsync(null);
    }
    
    /// <remarks/>
    public void getTServerInfoAsync(object userState) {
        if ((this.getTServerInfoOperationCompleted == null)) {
            this.getTServerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTServerInfoOperationCompleted);
        }
        this.InvokeAsync("getTServerInfo", new object[0], this.getTServerInfoOperationCompleted, userState);
    }
    
    private void OngetTServerInfoOperationCompleted(object arg) {
        if ((this.getTServerInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTServerInfoCompleted(this, new getTServerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#readJob", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] readJob([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int offset, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int len, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool waitUntilAvailable) {
        object[] results = this.Invoke("readJob", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginreadJob(int jobId, int offset, int len, bool waitUntilAvailable, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("readJob", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndreadJob(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void readJobAsync(int jobId, int offset, int len, bool waitUntilAvailable) {
        this.readJobAsync(jobId, offset, len, waitUntilAvailable, null);
    }
    
    /// <remarks/>
    public void readJobAsync(int jobId, int offset, int len, bool waitUntilAvailable, object userState) {
        if ((this.readJobOperationCompleted == null)) {
            this.readJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadJobOperationCompleted);
        }
        this.InvokeAsync("readJob", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable}, this.readJobOperationCompleted, userState);
    }
    
    private void OnreadJobOperationCompleted(object arg) {
        if ((this.readJobCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.readJobCompleted(this, new readJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#readJobDIME", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] readJobDIME([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int offset, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int len, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool waitUntilAvailable) {
        object[] results = this.Invoke("readJobDIME", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginreadJobDIME(int jobId, int offset, int len, bool waitUntilAvailable, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("readJobDIME", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndreadJobDIME(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void readJobDIMEAsync(int jobId, int offset, int len, bool waitUntilAvailable) {
        this.readJobDIMEAsync(jobId, offset, len, waitUntilAvailable, null);
    }
    
    /// <remarks/>
    public void readJobDIMEAsync(int jobId, int offset, int len, bool waitUntilAvailable, object userState) {
        if ((this.readJobDIMEOperationCompleted == null)) {
            this.readJobDIMEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadJobDIMEOperationCompleted);
        }
        this.InvokeAsync("readJobDIME", new object[] {
                    jobId,
                    offset,
                    len,
                    waitUntilAvailable}, this.readJobDIMEOperationCompleted, userState);
    }
    
    private void OnreadJobDIMEOperationCompleted(object arg) {
        if ((this.readJobDIMECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.readJobDIMECompleted(this, new readJobDIMECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#rescan", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void rescan() {
        this.Invoke("rescan", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginrescan(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("rescan", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void Endrescan(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void rescanAsync() {
        this.rescanAsync(null);
    }
    
    /// <remarks/>
    public void rescanAsync(object userState) {
        if ((this.rescanOperationCompleted == null)) {
            this.rescanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrescanOperationCompleted);
        }
        this.InvokeAsync("rescan", new object[0], this.rescanOperationCompleted, userState);
    }
    
    private void OnrescanOperationCompleted(object arg) {
        if ((this.rescanCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.rescanCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#removeJob", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void removeJob([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobId) {
        this.Invoke("removeJob", new object[] {
                    jobId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveJob(int jobId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeJob", new object[] {
                    jobId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndremoveJob(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void removeJobAsync(int jobId) {
        this.removeJobAsync(jobId, null);
    }
    
    /// <remarks/>
    public void removeJobAsync(int jobId, object userState) {
        if ((this.removeJobOperationCompleted == null)) {
            this.removeJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveJobOperationCompleted);
        }
        this.InvokeAsync("removeJob", new object[] {
                    jobId}, this.removeJobOperationCompleted, userState);
    }
    
    private void OnremoveJobOperationCompleted(object arg) {
        if ((this.removeJobCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeJobCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#removeJobRange", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void removeJobRange([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobFirst, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobLast) {
        this.Invoke("removeJobRange", new object[] {
                    jobFirst,
                    jobLast});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveJobRange(int jobFirst, int jobLast, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeJobRange", new object[] {
                    jobFirst,
                    jobLast}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndremoveJobRange(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void removeJobRangeAsync(int jobFirst, int jobLast) {
        this.removeJobRangeAsync(jobFirst, jobLast, null);
    }
    
    /// <remarks/>
    public void removeJobRangeAsync(int jobFirst, int jobLast, object userState) {
        if ((this.removeJobRangeOperationCompleted == null)) {
            this.removeJobRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveJobRangeOperationCompleted);
        }
        this.InvokeAsync("removeJobRange", new object[] {
                    jobFirst,
                    jobLast}, this.removeJobRangeOperationCompleted, userState);
    }
    
    private void OnremoveJobRangeOperationCompleted(object arg) {
        if ((this.removeJobRangeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeJobRangeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void removeJobRangeFiltered([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobFirst, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int jobLast, [System.Xml.Serialization.XmlElementAttribute("filterFlags", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] FilterFlag[] filterFlags, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
        this.Invoke("removeJobRangeFiltered", new object[] {
                    jobFirst,
                    jobLast,
                    filterFlags,
                    user});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveJobRangeFiltered(int jobFirst, int jobLast, FilterFlag[] filterFlags, string user, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeJobRangeFiltered", new object[] {
                    jobFirst,
                    jobLast,
                    filterFlags,
                    user}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndremoveJobRangeFiltered(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void removeJobRangeFilteredAsync(int jobFirst, int jobLast, FilterFlag[] filterFlags, string user) {
        this.removeJobRangeFilteredAsync(jobFirst, jobLast, filterFlags, user, null);
    }
    
    /// <remarks/>
    public void removeJobRangeFilteredAsync(int jobFirst, int jobLast, FilterFlag[] filterFlags, string user, object userState) {
        if ((this.removeJobRangeFilteredOperationCompleted == null)) {
            this.removeJobRangeFilteredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveJobRangeFilteredOperationCompleted);
        }
        this.InvokeAsync("removeJobRangeFiltered", new object[] {
                    jobFirst,
                    jobLast,
                    filterFlags,
                    user}, this.removeJobRangeFilteredOperationCompleted, userState);
    }
    
    private void OnremoveJobRangeFilteredOperationCompleted(object arg) {
        if ((this.removeJobRangeFilteredCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeJobRangeFilteredCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#uploadDictionary", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void uploadDictionary([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dictId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] text) {
        this.Invoke("uploadDictionary", new object[] {
                    dictId,
                    text});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadDictionary(string dictId, byte[] text, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadDictionary", new object[] {
                    dictId,
                    text}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnduploadDictionary(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void uploadDictionaryAsync(string dictId, byte[] text) {
        this.uploadDictionaryAsync(dictId, text, null);
    }
    
    /// <remarks/>
    public void uploadDictionaryAsync(string dictId, byte[] text, object userState) {
        if ((this.uploadDictionaryOperationCompleted == null)) {
            this.uploadDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadDictionaryOperationCompleted);
        }
        this.InvokeAsync("uploadDictionary", new object[] {
                    dictId,
                    text}, this.uploadDictionaryOperationCompleted, userState);
    }
    
    private void OnuploadDictionaryOperationCompleted(object arg) {
        if ((this.uploadDictionaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadDictionaryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#downloadDictionary", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] downloadDictionary([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dictId) {
        object[] results = this.Invoke("downloadDictionary", new object[] {
                    dictId});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindownloadDictionary(string dictId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("downloadDictionary", new object[] {
                    dictId}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EnddownloadDictionary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void downloadDictionaryAsync(string dictId) {
        this.downloadDictionaryAsync(dictId, null);
    }
    
    /// <remarks/>
    public void downloadDictionaryAsync(string dictId, object userState) {
        if ((this.downloadDictionaryOperationCompleted == null)) {
            this.downloadDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadDictionaryOperationCompleted);
        }
        this.InvokeAsync("downloadDictionary", new object[] {
                    dictId}, this.downloadDictionaryOperationCompleted, userState);
    }
    
    private void OndownloadDictionaryOperationCompleted(object arg) {
        if ((this.downloadDictionaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.downloadDictionaryCompleted(this, new downloadDictionaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#downloadDictionaryDIME", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] downloadDictionaryDIME([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dictId) {
        object[] results = this.Invoke("downloadDictionaryDIME", new object[] {
                    dictId});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindownloadDictionaryDIME(string dictId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("downloadDictionaryDIME", new object[] {
                    dictId}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EnddownloadDictionaryDIME(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void downloadDictionaryDIMEAsync(string dictId) {
        this.downloadDictionaryDIMEAsync(dictId, null);
    }
    
    /// <remarks/>
    public void downloadDictionaryDIMEAsync(string dictId, object userState) {
        if ((this.downloadDictionaryDIMEOperationCompleted == null)) {
            this.downloadDictionaryDIMEOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadDictionaryDIMEOperationCompleted);
        }
        this.InvokeAsync("downloadDictionaryDIME", new object[] {
                    dictId}, this.downloadDictionaryDIMEOperationCompleted, userState);
    }
    
    private void OndownloadDictionaryDIMEOperationCompleted(object arg) {
        if ((this.downloadDictionaryDIMECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.downloadDictionaryDIMECompleted(this, new downloadDictionaryDIMECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#removeDictionary", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void removeDictionary([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dictId) {
        this.Invoke("removeDictionary", new object[] {
                    dictId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveDictionary(string dictId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeDictionary", new object[] {
                    dictId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndremoveDictionary(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void removeDictionaryAsync(string dictId) {
        this.removeDictionaryAsync(dictId, null);
    }
    
    /// <remarks/>
    public void removeDictionaryAsync(string dictId, object userState) {
        if ((this.removeDictionaryOperationCompleted == null)) {
            this.removeDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveDictionaryOperationCompleted);
        }
        this.InvokeAsync("removeDictionary", new object[] {
                    dictId}, this.removeDictionaryOperationCompleted, userState);
    }
    
    private void OnremoveDictionaryOperationCompleted(object arg) {
        if ((this.removeDictionaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeDictionaryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#uploadCustomizer", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void uploadCustomizer([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customizeId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] text, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool overwriteExisting) {
        this.Invoke("uploadCustomizer", new object[] {
                    customizeId,
                    text,
                    overwriteExisting});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadCustomizer(string customizeId, byte[] text, bool overwriteExisting, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadCustomizer", new object[] {
                    customizeId,
                    text,
                    overwriteExisting}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnduploadCustomizer(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void uploadCustomizerAsync(string customizeId, byte[] text, bool overwriteExisting) {
        this.uploadCustomizerAsync(customizeId, text, overwriteExisting, null);
    }
    
    /// <remarks/>
    public void uploadCustomizerAsync(string customizeId, byte[] text, bool overwriteExisting, object userState) {
        if ((this.uploadCustomizerOperationCompleted == null)) {
            this.uploadCustomizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadCustomizerOperationCompleted);
        }
        this.InvokeAsync("uploadCustomizer", new object[] {
                    customizeId,
                    text,
                    overwriteExisting}, this.uploadCustomizerOperationCompleted, userState);
    }
    
    private void OnuploadCustomizerOperationCompleted(object arg) {
        if ((this.uploadCustomizerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadCustomizerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#downloadCustomizer", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] downloadCustomizer([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customizeId) {
        object[] results = this.Invoke("downloadCustomizer", new object[] {
                    customizeId});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindownloadCustomizer(string customizeId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("downloadCustomizer", new object[] {
                    customizeId}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EnddownloadCustomizer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void downloadCustomizerAsync(string customizeId) {
        this.downloadCustomizerAsync(customizeId, null);
    }
    
    /// <remarks/>
    public void downloadCustomizerAsync(string customizeId, object userState) {
        if ((this.downloadCustomizerOperationCompleted == null)) {
            this.downloadCustomizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadCustomizerOperationCompleted);
        }
        this.InvokeAsync("downloadCustomizer", new object[] {
                    customizeId}, this.downloadCustomizerOperationCompleted, userState);
    }
    
    private void OndownloadCustomizerOperationCompleted(object arg) {
        if ((this.downloadCustomizerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.downloadCustomizerCompleted(this, new downloadCustomizerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#downloadCustomizerDIME", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] downloadCustomizerDIME([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customizeId) {
        object[] results = this.Invoke("downloadCustomizerDIME", new object[] {
                    customizeId});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindownloadCustomizerDIME(string customizeId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("downloadCustomizerDIME", new object[] {
                    customizeId}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EnddownloadCustomizerDIME(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void downloadCustomizerDIMEAsync(string customizeId) {
        this.downloadCustomizerDIMEAsync(customizeId, null);
    }
    
    /// <remarks/>
    public void downloadCustomizerDIMEAsync(string customizeId, object userState) {
        if ((this.downloadCustomizerDIMEOperationCompleted == null)) {
            this.downloadCustomizerDIMEOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadCustomizerDIMEOperationCompleted);
        }
        this.InvokeAsync("downloadCustomizerDIME", new object[] {
                    customizeId}, this.downloadCustomizerDIMEOperationCompleted, userState);
    }
    
    private void OndownloadCustomizerDIMEOperationCompleted(object arg) {
        if ((this.downloadCustomizerDIMECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.downloadCustomizerDIMECompleted(this, new downloadCustomizerDIMECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:lwq#removeCustomizer", RequestNamespace="http://www.languageweaver.com/LWQueue", ResponseNamespace="http://www.languageweaver.com/LWQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void removeCustomizer([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customizeId) {
        this.Invoke("removeCustomizer", new object[] {
                    customizeId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveCustomizer(string customizeId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeCustomizer", new object[] {
                    customizeId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndremoveCustomizer(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void removeCustomizerAsync(string customizeId) {
        this.removeCustomizerAsync(customizeId, null);
    }
    
    /// <remarks/>
    public void removeCustomizerAsync(string customizeId, object userState) {
        if ((this.removeCustomizerOperationCompleted == null)) {
            this.removeCustomizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveCustomizerOperationCompleted);
        }
        this.InvokeAsync("removeCustomizer", new object[] {
                    customizeId}, this.removeCustomizerOperationCompleted, userState);
    }
    
    private void OnremoveCustomizerOperationCompleted(object arg) {
        if ((this.removeCustomizerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeCustomizerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public enum FilterFlag {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("HIGH-PRI")]
    HIGHPRI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("NORM-PRI")]
    NORMPRI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IN-PROGRESS")]
    INPROGRESS,
    
    /// <remarks/>
    WAITING,
    
    /// <remarks/>
    FINISHED,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FINISHED-WITH-ERROR")]
    FINISHEDWITHERROR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class JobHeader {
    
    private TranslationContext translationContextField;
    
    private string errorMessageField;
    
    private string warningsField;
    
    private int jobIdField;
    
    private JobParam jobParamField;
    
    private int progressField;
    
    private int rateField;
    
    private int wordCountField;
    
    private int inputSizeField;
    
    private int outputSizeField;
    
    private bool stellentUsedField;
    
    private JobState stateField;
    
    private System.DateTime timeSubmittedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public TranslationContext translationContext {
        get {
            return this.translationContextField;
        }
        set {
            this.translationContextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string errorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warnings {
        get {
            return this.warningsField;
        }
        set {
            this.warningsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int jobId {
        get {
            return this.jobIdField;
        }
        set {
            this.jobIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public JobParam jobParam {
        get {
            return this.jobParamField;
        }
        set {
            this.jobParamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int progress {
        get {
            return this.progressField;
        }
        set {
            this.progressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int wordCount {
        get {
            return this.wordCountField;
        }
        set {
            this.wordCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int inputSize {
        get {
            return this.inputSizeField;
        }
        set {
            this.inputSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int outputSize {
        get {
            return this.outputSizeField;
        }
        set {
            this.outputSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool stellentUsed {
        get {
            return this.stellentUsedField;
        }
        set {
            this.stellentUsedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public JobState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime timeSubmitted {
        get {
            return this.timeSubmittedField;
        }
        set {
            this.timeSubmittedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class TranslationContext {
    
    private string[] withDictionaryField;
    
    private string[] withCustomizerField;
    
    private string targetLangIdField;
    
    private string encodingField;
    
    private bool markTransliteratedField;
    
    private bool markUnknownField;
    
    private bool markDictionaryField;
    
    private bool markSegmentsField;
    
    private bool confIndWordField;
    
    private bool confIndSentenceField;
    
    private string inputFormatField;
    
    private string outputFormatField;
    
    private int translationQualityField;
    
    private bool showTransliteratedField;
    
    private bool showUnknownField;
    
    private bool hasFramesField;
    
    private bool encodingWasDetectedField;
    
    private bool encodingWasDetectedFieldSpecified;
    
    private string sourceLangIdField;
    
    public TranslationContext() {
        this.markTransliteratedField = false;
        this.markUnknownField = false;
        this.markDictionaryField = false;
        this.markSegmentsField = false;
        this.confIndWordField = false;
        this.confIndSentenceField = false;
        this.translationQualityField = 2;
        this.showTransliteratedField = false;
        this.showUnknownField = true;
        this.hasFramesField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("withDictionary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] withDictionary {
        get {
            return this.withDictionaryField;
        }
        set {
            this.withDictionaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("withCustomizer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] withCustomizer {
        get {
            return this.withCustomizerField;
        }
        set {
            this.withCustomizerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string targetLangId {
        get {
            return this.targetLangIdField;
        }
        set {
            this.targetLangIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool markTransliterated {
        get {
            return this.markTransliteratedField;
        }
        set {
            this.markTransliteratedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool markUnknown {
        get {
            return this.markUnknownField;
        }
        set {
            this.markUnknownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool markDictionary {
        get {
            return this.markDictionaryField;
        }
        set {
            this.markDictionaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool markSegments {
        get {
            return this.markSegmentsField;
        }
        set {
            this.markSegmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool confIndWord {
        get {
            return this.confIndWordField;
        }
        set {
            this.confIndWordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool confIndSentence {
        get {
            return this.confIndSentenceField;
        }
        set {
            this.confIndSentenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string inputFormat {
        get {
            return this.inputFormatField;
        }
        set {
            this.inputFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string outputFormat {
        get {
            return this.outputFormatField;
        }
        set {
            this.outputFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(2)]
    public int translationQuality {
        get {
            return this.translationQualityField;
        }
        set {
            this.translationQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool showTransliterated {
        get {
            return this.showTransliteratedField;
        }
        set {
            this.showTransliteratedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool showUnknown {
        get {
            return this.showUnknownField;
        }
        set {
            this.showUnknownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool hasFrames {
        get {
            return this.hasFramesField;
        }
        set {
            this.hasFramesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool encodingWasDetected {
        get {
            return this.encodingWasDetectedField;
        }
        set {
            this.encodingWasDetectedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool encodingWasDetectedSpecified {
        get {
            return this.encodingWasDetectedFieldSpecified;
        }
        set {
            this.encodingWasDetectedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceLangId {
        get {
            return this.sourceLangIdField;
        }
        set {
            this.sourceLangIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class TServerStat {
    
    private string statusField;
    
    private int contextSwitchesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int contextSwitches {
        get {
            return this.contextSwitchesField;
        }
        set {
            this.contextSwitchesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class TServerInfo {
    
    private string urlField;
    
    private LangPairInfo activeLangPairField;
    
    private LangPairInfo[] langPairsField;
    
    private TServerStat statisticsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public LangPairInfo activeLangPair {
        get {
            return this.activeLangPairField;
        }
        set {
            this.activeLangPairField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("langPairs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LangPairInfo[] langPairs {
        get {
            return this.langPairsField;
        }
        set {
            this.langPairsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public TServerStat statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class LangPairInfo {
    
    private string sourceLangField;
    
    private string sourceLangIdField;
    
    private string targetLangField;
    
    private string targetLangIdField;
    
    private string langHashIdField;
    
    private string[] encodingsField;
    
    private string[] featuresField;
    
    private DictionaryInfo[] availableDictionariesField;
    
    private CustomizerInfo[] availableCustomizersField;
    
    private long wordsLeftField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceLang {
        get {
            return this.sourceLangField;
        }
        set {
            this.sourceLangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceLangId {
        get {
            return this.sourceLangIdField;
        }
        set {
            this.sourceLangIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string targetLang {
        get {
            return this.targetLangField;
        }
        set {
            this.targetLangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string targetLangId {
        get {
            return this.targetLangIdField;
        }
        set {
            this.targetLangIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string langHashId {
        get {
            return this.langHashIdField;
        }
        set {
            this.langHashIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("encodings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] encodings {
        get {
            return this.encodingsField;
        }
        set {
            this.encodingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("features", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] features {
        get {
            return this.featuresField;
        }
        set {
            this.featuresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("availableDictionaries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DictionaryInfo[] availableDictionaries {
        get {
            return this.availableDictionariesField;
        }
        set {
            this.availableDictionariesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("availableCustomizers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CustomizerInfo[] availableCustomizers {
        get {
            return this.availableCustomizersField;
        }
        set {
            this.availableCustomizersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long wordsLeft {
        get {
            return this.wordsLeftField;
        }
        set {
            this.wordsLeftField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class DictionaryInfo {
    
    private string dictIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dictId {
        get {
            return this.dictIdField;
        }
        set {
            this.dictIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class CustomizerInfo {
    
    private string customizerIdField;
    
    private string descriptionField;
    
    private string langPairDescField;
    
    private System.DateTime creationTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customizerId {
        get {
            return this.customizerIdField;
        }
        set {
            this.customizerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string langPairDesc {
        get {
            return this.langPairDescField;
        }
        set {
            this.langPairDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime creationTime {
        get {
            return this.creationTimeField;
        }
        set {
            this.creationTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class ServerStat {
    
    private int documentsInQueueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int documentsInQueue {
        get {
            return this.documentsInQueueField;
        }
        set {
            this.documentsInQueueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class ServerInfo {
    
    private string versionField;
    
    private LangPairInfo[] langPairsField;
    
    private ServerStat statisticsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("langPairs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LangPairInfo[] langPairs {
        get {
            return this.langPairsField;
        }
        set {
            this.langPairsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ServerStat statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public partial class JobParam {
    
    private int prioField;
    
    private bool prioFieldSpecified;
    
    private string titleField;
    
    private string urlField;
    
    private string userField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int prio {
        get {
            return this.prioField;
        }
        set {
            this.prioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool prioSpecified {
        get {
            return this.prioFieldSpecified;
        }
        set {
            this.prioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.languageweaver.com/LWQueue")]
public enum JobState {
    
    /// <remarks/>
    INIT,
    
    /// <remarks/>
    READY,
    
    /// <remarks/>
    TRANSLATING,
    
    /// <remarks/>
    CANCELLING,
    
    /// <remarks/>
    UPLOADING,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOWNLOADING-URL")]
    DOWNLOADINGURL,
    
    /// <remarks/>
    DONE,
    
    /// <remarks/>
    FAILED,
    
    /// <remarks/>
    TERMINATED,
    
    /// <remarks/>
    DELETING,
    
    /// <remarks/>
    TRANSFORMING,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void browseJobsCompletedEventHandler(object sender, browseJobsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class browseJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal browseJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public JobHeader[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((JobHeader[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void cancelJobCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void changeJobPrioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void createJobCompletedEventHandler(object sender, createJobCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void translateStringCompletedEventHandler(object sender, translateStringCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class translateStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal translateStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getJobStatusCompletedEventHandler(object sender, getJobStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getJobStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getJobStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public JobHeader Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((JobHeader)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getServerInfoCompletedEventHandler(object sender, getServerInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getServerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getServerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ServerInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ServerInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getTServerInfoCompletedEventHandler(object sender, getTServerInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTServerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTServerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TServerInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TServerInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void readJobCompletedEventHandler(object sender, readJobCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class readJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal readJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void readJobDIMECompletedEventHandler(object sender, readJobDIMECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class readJobDIMECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal readJobDIMECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void rescanCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeJobCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeJobRangeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeJobRangeFilteredCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void uploadDictionaryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void downloadDictionaryCompletedEventHandler(object sender, downloadDictionaryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class downloadDictionaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal downloadDictionaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void downloadDictionaryDIMECompletedEventHandler(object sender, downloadDictionaryDIMECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class downloadDictionaryDIMECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal downloadDictionaryDIMECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeDictionaryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void uploadCustomizerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void downloadCustomizerCompletedEventHandler(object sender, downloadCustomizerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class downloadCustomizerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal downloadCustomizerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void downloadCustomizerDIMECompletedEventHandler(object sender, downloadCustomizerDIMECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class downloadCustomizerDIMECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal downloadCustomizerDIMECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeCustomizerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
