//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaMosaik.Logger.StressTest.Logger {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogEntry", Namespace="http://schemas.datacontract.org/2004/07/AlphaMosaik.Logger.Service")]
    [System.SerializableAttribute()]
    public partial class LogEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlphaMosaik.Logger.StressTest.Logger.LogEntryLevel LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlphaMosaik.Logger.StressTest.Logger.LogEntryLevel Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogEntryLevel", Namespace="http://schemas.datacontract.org/2004/07/AlphaMosaik.Logger")]
    public enum LogEntryLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debugging = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trace = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 400,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Logger.ILogger")]
    public interface ILogger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/LogEntry", ReplyAction="http://tempuri.org/ILogger/LogEntryResponse")]
        void LogEntry(AlphaMosaik.Logger.StressTest.Logger.LogEntry entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/LogMessage", ReplyAction="http://tempuri.org/ILogger/LogMessageResponse")]
        void LogMessage(string message, AlphaMosaik.Logger.StressTest.Logger.LogEntryLevel level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/LogException", ReplyAction="http://tempuri.org/ILogger/LogExceptionResponse")]
        void LogException(System.Exception exception);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggerChannel : AlphaMosaik.Logger.StressTest.Logger.ILogger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggerClient : System.ServiceModel.ClientBase<AlphaMosaik.Logger.StressTest.Logger.ILogger>, AlphaMosaik.Logger.StressTest.Logger.ILogger {
        
        public LoggerClient() {
        }
        
        public LoggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogEntry(AlphaMosaik.Logger.StressTest.Logger.LogEntry entry) {
            base.Channel.LogEntry(entry);
        }
        
        public void LogMessage(string message, AlphaMosaik.Logger.StressTest.Logger.LogEntryLevel level) {
            base.Channel.LogMessage(message, level);
        }
        
        public void LogException(System.Exception exception) {
            base.Channel.LogException(exception);
        }
    }
}
