//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Alphamosaik.Oceanik.AutomaticTranslation {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SystranTranslationSoapBinding", Namespace="http://www.systransoft.com/soap/api/5.2")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Option))]
    public partial class SystranTranslationWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TranslateOperationCompleted;
        
        private System.Threading.SendOrPostCallback PartOfSpeechTaggerOperationCompleted;
        
        private System.Threading.SendOrPostCallback DictCompileOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnalyseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DictSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterToXliffOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterFromXliffOperationCompleted;
        
        private System.Threading.SendOrPostCallback TermExtractOperationCompleted;
        
        /// <remarks/>
        public SystranTranslationWebService() {
            this.Url = "http://localhost:10000";
        }
        
        /// <remarks/>
        public event TranslateCompletedEventHandler TranslateCompleted;
        
        /// <remarks/>
        public event PartOfSpeechTaggerCompletedEventHandler PartOfSpeechTaggerCompleted;
        
        /// <remarks/>
        public event DictCompileCompletedEventHandler DictCompileCompleted;
        
        /// <remarks/>
        public event AnalyseCompletedEventHandler AnalyseCompleted;
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        public event UpdateInfoCompletedEventHandler UpdateInfoCompleted;
        
        /// <remarks/>
        public event DictSearchCompletedEventHandler DictSearchCompleted;
        
        /// <remarks/>
        public event FilterTypeCompletedEventHandler FilterTypeCompleted;
        
        /// <remarks/>
        public event FilterToXliffCompletedEventHandler FilterToXliffCompleted;
        
        /// <remarks/>
        public event FilterFromXliffCompletedEventHandler FilterFromXliffCompleted;
        
        /// <remarks/>
        public event TermExtractCompletedEventHandler TermExtractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/Translate", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response Translate(Request request) {
            object[] results = this.Invoke("Translate", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTranslate(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Translate", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndTranslate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void TranslateAsync(Request request) {
            this.TranslateAsync(request, null);
        }
        
        /// <remarks/>
        public void TranslateAsync(Request request, object userState) {
            if ((this.TranslateOperationCompleted == null)) {
                this.TranslateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateOperationCompleted);
            }
            this.InvokeAsync("Translate", new object[] {
                        request}, this.TranslateOperationCompleted, userState);
        }
        
        private void OnTranslateOperationCompleted(object arg) {
            if ((this.TranslateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslateCompleted(this, new TranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/PartOfSpeechTagger", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response PartOfSpeechTagger(Request request) {
            object[] results = this.Invoke("PartOfSpeechTagger", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPartOfSpeechTagger(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PartOfSpeechTagger", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndPartOfSpeechTagger(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PartOfSpeechTaggerAsync(Request request) {
            this.PartOfSpeechTaggerAsync(request, null);
        }
        
        /// <remarks/>
        public void PartOfSpeechTaggerAsync(Request request, object userState) {
            if ((this.PartOfSpeechTaggerOperationCompleted == null)) {
                this.PartOfSpeechTaggerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPartOfSpeechTaggerOperationCompleted);
            }
            this.InvokeAsync("PartOfSpeechTagger", new object[] {
                        request}, this.PartOfSpeechTaggerOperationCompleted, userState);
        }
        
        private void OnPartOfSpeechTaggerOperationCompleted(object arg) {
            if ((this.PartOfSpeechTaggerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PartOfSpeechTaggerCompleted(this, new PartOfSpeechTaggerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/DictCompile", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response DictCompile(Request request) {
            object[] results = this.Invoke("DictCompile", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictCompile(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DictCompile", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndDictCompile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void DictCompileAsync(Request request) {
            this.DictCompileAsync(request, null);
        }
        
        /// <remarks/>
        public void DictCompileAsync(Request request, object userState) {
            if ((this.DictCompileOperationCompleted == null)) {
                this.DictCompileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDictCompileOperationCompleted);
            }
            this.InvokeAsync("DictCompile", new object[] {
                        request}, this.DictCompileOperationCompleted, userState);
        }
        
        private void OnDictCompileOperationCompleted(object arg) {
            if ((this.DictCompileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DictCompileCompleted(this, new DictCompileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/Analyse", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response Analyse(Request request) {
            object[] results = this.Invoke("Analyse", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAnalyse(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Analyse", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndAnalyse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void AnalyseAsync(Request request) {
            this.AnalyseAsync(request, null);
        }
        
        /// <remarks/>
        public void AnalyseAsync(Request request, object userState) {
            if ((this.AnalyseOperationCompleted == null)) {
                this.AnalyseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalyseOperationCompleted);
            }
            this.InvokeAsync("Analyse", new object[] {
                        request}, this.AnalyseOperationCompleted, userState);
        }
        
        private void OnAnalyseOperationCompleted(object arg) {
            if ((this.AnalyseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalyseCompleted(this, new AnalyseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/GetInfo", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response GetInfo(RequestInfo request) {
            object[] results = this.Invoke("GetInfo", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInfo(RequestInfo request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInfo", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndGetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync(RequestInfo request) {
            this.GetInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(RequestInfo request, object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[] {
                        request}, this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/UpdateInfo", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response UpdateInfo(RequestInfo request) {
            object[] results = this.Invoke("UpdateInfo", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateInfo(RequestInfo request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateInfo", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndUpdateInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInfoAsync(RequestInfo request) {
            this.UpdateInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void UpdateInfoAsync(RequestInfo request, object userState) {
            if ((this.UpdateInfoOperationCompleted == null)) {
                this.UpdateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateInfo", new object[] {
                        request}, this.UpdateInfoOperationCompleted, userState);
        }
        
        private void OnUpdateInfoOperationCompleted(object arg) {
            if ((this.UpdateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInfoCompleted(this, new UpdateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/DictSearch", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response DictSearch(Request request, DictSearchRequest dictSearchRequest) {
            object[] results = this.Invoke("DictSearch", new object[] {
                        request,
                        dictSearchRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictSearch(Request request, DictSearchRequest dictSearchRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DictSearch", new object[] {
                        request,
                        dictSearchRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndDictSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void DictSearchAsync(Request request, DictSearchRequest dictSearchRequest) {
            this.DictSearchAsync(request, dictSearchRequest, null);
        }
        
        /// <remarks/>
        public void DictSearchAsync(Request request, DictSearchRequest dictSearchRequest, object userState) {
            if ((this.DictSearchOperationCompleted == null)) {
                this.DictSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDictSearchOperationCompleted);
            }
            this.InvokeAsync("DictSearch", new object[] {
                        request,
                        dictSearchRequest}, this.DictSearchOperationCompleted, userState);
        }
        
        private void OnDictSearchOperationCompleted(object arg) {
            if ((this.DictSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DictSearchCompleted(this, new DictSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/FilterType", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response FilterType(Request request) {
            object[] results = this.Invoke("FilterType", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFilterType(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FilterType", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndFilterType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void FilterTypeAsync(Request request) {
            this.FilterTypeAsync(request, null);
        }
        
        /// <remarks/>
        public void FilterTypeAsync(Request request, object userState) {
            if ((this.FilterTypeOperationCompleted == null)) {
                this.FilterTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterTypeOperationCompleted);
            }
            this.InvokeAsync("FilterType", new object[] {
                        request}, this.FilterTypeOperationCompleted, userState);
        }
        
        private void OnFilterTypeOperationCompleted(object arg) {
            if ((this.FilterTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterTypeCompleted(this, new FilterTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/FilterToXliff", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response FilterToXliff(Request request) {
            object[] results = this.Invoke("FilterToXliff", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFilterToXliff(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FilterToXliff", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndFilterToXliff(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void FilterToXliffAsync(Request request) {
            this.FilterToXliffAsync(request, null);
        }
        
        /// <remarks/>
        public void FilterToXliffAsync(Request request, object userState) {
            if ((this.FilterToXliffOperationCompleted == null)) {
                this.FilterToXliffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterToXliffOperationCompleted);
            }
            this.InvokeAsync("FilterToXliff", new object[] {
                        request}, this.FilterToXliffOperationCompleted, userState);
        }
        
        private void OnFilterToXliffOperationCompleted(object arg) {
            if ((this.FilterToXliffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterToXliffCompleted(this, new FilterToXliffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/FilterFromXliff", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response FilterFromXliff(Request request) {
            object[] results = this.Invoke("FilterFromXliff", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFilterFromXliff(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FilterFromXliff", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndFilterFromXliff(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void FilterFromXliffAsync(Request request) {
            this.FilterFromXliffAsync(request, null);
        }
        
        /// <remarks/>
        public void FilterFromXliffAsync(Request request, object userState) {
            if ((this.FilterFromXliffOperationCompleted == null)) {
                this.FilterFromXliffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterFromXliffOperationCompleted);
            }
            this.InvokeAsync("FilterFromXliff", new object[] {
                        request}, this.FilterFromXliffOperationCompleted, userState);
        }
        
        private void OnFilterFromXliffOperationCompleted(object arg) {
            if ((this.FilterFromXliffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterFromXliffCompleted(this, new FilterFromXliffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.systransoft.com/TermExtract", RequestNamespace="http://www.systransoft.com/soap/api/5.2", ResponseNamespace="http://www.systransoft.com/soap/api/5.2")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response TermExtract(Request request) {
            object[] results = this.Invoke("TermExtract", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTermExtract(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TermExtract", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndTermExtract(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void TermExtractAsync(Request request) {
            this.TermExtractAsync(request, null);
        }
        
        /// <remarks/>
        public void TermExtractAsync(Request request, object userState) {
            if ((this.TermExtractOperationCompleted == null)) {
                this.TermExtractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTermExtractOperationCompleted);
            }
            this.InvokeAsync("TermExtract", new object[] {
                        request}, this.TermExtractOperationCompleted, userState);
        }
        
        private void OnTermExtractOperationCompleted(object arg) {
            if ((this.TermExtractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TermExtractCompleted(this, new TermExtractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.systransoft.com/soap/api/5.2")]
    public partial class Request {
        
        private string requestidField;
        
        private Option[] optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
            }
        }
        
        /// <remarks/>
        public Option[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.systransoft.com/soap/api/5.2")]
    public partial class Option {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.systransoft.com/soap/api/5.2")]
    public partial class DictSearchRequest {
        
        private string langField;
        
        private string pathField;
        
        private string domainField;
        
        private string patternField;
        
        private string searchModeField;
        
        private string searchFieldField;
        
        private string spellcheckField;
        
        private System.Nullable<int> autocompletionField;
        
        private bool autocompletionFieldSpecified;
        
        private System.Nullable<int> limit_meaningsField;
        
        private bool limit_meaningsFieldSpecified;
        
        private System.Nullable<int> limit_expressionsField;
        
        private bool limit_expressionsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        public string searchMode {
            get {
                return this.searchModeField;
            }
            set {
                this.searchModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string searchField {
            get {
                return this.searchFieldField;
            }
            set {
                this.searchFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spellcheck {
            get {
                return this.spellcheckField;
            }
            set {
                this.spellcheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> autocompletion {
            get {
                return this.autocompletionField;
            }
            set {
                this.autocompletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool autocompletionSpecified {
            get {
                return this.autocompletionFieldSpecified;
            }
            set {
                this.autocompletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> limit_meanings {
            get {
                return this.limit_meaningsField;
            }
            set {
                this.limit_meaningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool limit_meaningsSpecified {
            get {
                return this.limit_meaningsFieldSpecified;
            }
            set {
                this.limit_meaningsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> limit_expressions {
            get {
                return this.limit_expressionsField;
            }
            set {
                this.limit_expressionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool limit_expressionsSpecified {
            get {
                return this.limit_expressionsFieldSpecified;
            }
            set {
                this.limit_expressionsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.systransoft.com/soap/api/5.2")]
    public partial class RequestInfo {
        
        private string infotypeField;
        
        private string requestidField;
        
        private Option[] optionField;
        
        /// <remarks/>
        public string infotype {
            get {
                return this.infotypeField;
            }
            set {
                this.infotypeField = value;
            }
        }
        
        /// <remarks/>
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
            }
        }
        
        /// <remarks/>
        public Option[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.systransoft.com/soap/api/5.2")]
    public partial class Response {
        
        private string infotypeField;
        
        private string requestidField;
        
        private Option[] optionField;
        
        /// <remarks/>
        public string infotype {
            get {
                return this.infotypeField;
            }
            set {
                this.infotypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
            }
        }
        
        /// <remarks/>
        public Option[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void TranslateCompletedEventHandler(object sender, TranslateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void PartOfSpeechTaggerCompletedEventHandler(object sender, PartOfSpeechTaggerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartOfSpeechTaggerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PartOfSpeechTaggerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DictCompileCompletedEventHandler(object sender, DictCompileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DictCompileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DictCompileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void AnalyseCompletedEventHandler(object sender, AnalyseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalyseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalyseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateInfoCompletedEventHandler(object sender, UpdateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DictSearchCompletedEventHandler(object sender, DictSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DictSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DictSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void FilterTypeCompletedEventHandler(object sender, FilterTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void FilterToXliffCompletedEventHandler(object sender, FilterToXliffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterToXliffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterToXliffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void FilterFromXliffCompletedEventHandler(object sender, FilterFromXliffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterFromXliffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterFromXliffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void TermExtractCompletedEventHandler(object sender, TermExtractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TermExtractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TermExtractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}
