// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class UIMap
    {
        /// <summary>
        /// AccesAuSite - Use 'AccesAuSiteParams' to pass parameters into this method.
        /// </summary>
        public void AccesAuSite()
        {
            #region Variable Declarations
            WinButton uINewTabCtrlTButton = this.UIHowtoAssociateanAutoWindow.UITabRowTabList.UINewTabCtrlTButton;
            BrowserWindow uIHowtoAssociateanAutoWindow = this.UIHowtoAssociateanAutoWindow;
            HtmlCell uIItemCell = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalQDocument.UIPlacementCell.UIItemTable.UIItemCell;
            HtmlImage uISolutions1InfrastrucImage = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalQDocument.UIInfraTechnoCell.UISolutions1InfrastrucImage;
            HtmlHyperlink uIInfrastructureetSécuHyperlink = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalSDocument.UICtl00_PlaceHolderAlpPane.UIInfrastructureetSécuHyperlink;
            #endregion

            // Click 'New Tab (Ctrl+T)' button
            Mouse.Click(uINewTabCtrlTButton, new Point(10, 13));

            // Go to web page 'http://alphamosaik.com/'
            uIHowtoAssociateanAutoWindow.NavigateToUrl(new System.Uri(this.AccesAuSiteParams.UIHowtoAssociateanAutoWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Unknown Name' cell at (16, 71)
            Mouse.Hover(uIItemCell, new Point(16, 71));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click '/Solutions1/InfrastructureTechnologique.png' image
            Mouse.Click(uISolutions1InfrastrucImage, new Point(84, 40));

            // Click 'Infrastructure et Sécurité' link
            Mouse.Click(uIInfrastructureetSécuHyperlink, new Point(66, 10));
        }
        
        /// <summary>
        /// LIMethod - Use 'LIMethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void LIMethod()
        {
            #region Variable Declarations
            HtmlCustom uIConseillerlesentreprCustom = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalSDocument1.UICtl00_PlaceHolderAlpPane.UIConseillerlesentreprCustom;
            #endregion

            // Verify that 'Conseiller les entreprises sur les solut' custom control's property 'TagName' equals 'LI'
            Assert.AreEqual(this.LIMethodExpectedValues.UIConseillerlesentreprCustomTagName, uIConseillerlesentreprCustom.TagName);
        }
        
        /// <summary>
        /// ApplicationsMethod
        /// </summary>
        public void ApplicationsMethod()
        {
            #region Variable Declarations
            HtmlCustom uIAnalyserlesbesoinsenCustom = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalSDocument1.UICtl00_PlaceHolderAlpPane.UIAnalyserlesbesoinsenCustom;
            HtmlHyperlink uIApplicationsHyperlink = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalSDocument1.UIZz2_CurrentNavPane.UIApplicationsHyperlink;
            HtmlHyperlink uIModuleMultilingueHyperlink = this.UIHowtoAssociateanAutoWindow.UIAlphaMosaïkMontréalSDocument11.UICtl00_PlaceHolderAlpPane.UIModuleMultilingueHyperlink;
            #endregion

            // Click 'Analyser les besoins en infrastructure d' custom control
            Mouse.Click(uIAnalyserlesbesoinsenCustom, new Point(496, 19));

            // Click 'Applications' link
            Mouse.Click(uIApplicationsHyperlink, new Point(75, 20));

            // Click 'Module Multilingue' link
            Mouse.Click(uIModuleMultilingueHyperlink, new Point(47, 7));
        }
        
        #region Properties
        public virtual SenghorMethodParams SenghorMethodParams
        {
            get
            {
                if ((this.mSenghorMethodParams == null))
                {
                    this.mSenghorMethodParams = new SenghorMethodParams();
                }
                return this.mSenghorMethodParams;
            }
        }
        
        public virtual SommaireMethodExpectedValues SommaireMethodExpectedValues
        {
            get
            {
                if ((this.mSommaireMethodExpectedValues == null))
                {
                    this.mSommaireMethodExpectedValues = new SommaireMethodExpectedValues();
                }
                return this.mSommaireMethodExpectedValues;
            }
        }
        
        public virtual AccesAuSiteParams AccesAuSiteParams
        {
            get
            {
                if ((this.mAccesAuSiteParams == null))
                {
                    this.mAccesAuSiteParams = new AccesAuSiteParams();
                }
                return this.mAccesAuSiteParams;
            }
        }
        
        public virtual LIMethodExpectedValues LIMethodExpectedValues
        {
            get
            {
                if ((this.mLIMethodExpectedValues == null))
                {
                    this.mLIMethodExpectedValues = new LIMethodExpectedValues();
                }
                return this.mLIMethodExpectedValues;
            }
        }
        
        public UIRunningapplicationsWindow UIRunningapplicationsWindow
        {
            get
            {
                if ((this.mUIRunningapplicationsWindow == null))
                {
                    this.mUIRunningapplicationsWindow = new UIRunningapplicationsWindow();
                }
                return this.mUIRunningapplicationsWindow;
            }
        }
        
        public UIJumpListWindow UIJumpListWindow
        {
            get
            {
                if ((this.mUIJumpListWindow == null))
                {
                    this.mUIJumpListWindow = new UIJumpListWindow();
                }
                return this.mUIJumpListWindow;
            }
        }
        
        public UIGoogleWindowsInterneWindow UIGoogleWindowsInterneWindow
        {
            get
            {
                if ((this.mUIGoogleWindowsInterneWindow == null))
                {
                    this.mUIGoogleWindowsInterneWindow = new UIGoogleWindowsInterneWindow();
                }
                return this.mUIGoogleWindowsInterneWindow;
            }
        }
        
        public UIHowtoAssociateanAutoWindow UIHowtoAssociateanAutoWindow
        {
            get
            {
                if ((this.mUIHowtoAssociateanAutoWindow == null))
                {
                    this.mUIHowtoAssociateanAutoWindow = new UIHowtoAssociateanAutoWindow();
                }
                return this.mUIHowtoAssociateanAutoWindow;
            }
        }
        #endregion
        
        #region Fields
        private SenghorMethodParams mSenghorMethodParams;
        
        private SommaireMethodExpectedValues mSommaireMethodExpectedValues;
        
        private AccesAuSiteParams mAccesAuSiteParams;
        
        private LIMethodExpectedValues mLIMethodExpectedValues;
        
        private UIRunningapplicationsWindow mUIRunningapplicationsWindow;
        
        private UIJumpListWindow mUIJumpListWindow;
        
        private UIGoogleWindowsInterneWindow mUIGoogleWindowsInterneWindow;
        
        private UIHowtoAssociateanAutoWindow mUIHowtoAssociateanAutoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SenghorMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SenghorMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'l' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText = "l";
        
        /// <summary>
        /// Type 'eopol' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys = "eopol";
        
        /// <summary>
        /// Type 'd' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys1 = "d";
        
        /// <summary>
        /// Type '{Back}e' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys2 = "{Back}e";
        
        /// <summary>
        /// Type 'lpol' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText1 = "lpol";
        
        /// <summary>
        /// Type 'd' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys3 = "d";
        
        /// <summary>
        /// Type '{Back}{Back}{Back}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys4 = "{Back}{Back}{Back}";
        
        /// <summary>
        /// Type '{Back}{Back}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys5 = "{Back}{Back}";
        
        /// <summary>
        /// Type '{Back}{Back}{Back}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys6 = "{Back}{Back}{Back}";
        
        /// <summary>
        /// Type 'lp' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText2 = "lp";
        
        /// <summary>
        /// Type '{Back}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys7 = "{Back}";
        
        /// <summary>
        /// Type '{Back}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys8 = "{Back}";
        
        /// <summary>
        /// Type 'leopol' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText3 = "leopol";
        
        /// <summary>
        /// Type 'leopold s' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText4 = "leopold s";
        
        /// <summary>
        /// Type 'e' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys9 = "e";
        
        /// <summary>
        /// Type 'leopold sedar senghor' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditText5 = "leopold sedar senghor";
        
        /// <summary>
        /// Type '{Enter}' in 'Rechercher' text box
        /// </summary>
        public string UIRechercherEditSendKeys10 = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SommaireMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SommaireMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'toc' table's property 'Id' equals 'toc'
        /// </summary>
        public string UITocTableId = "toc";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AccesAuSite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class AccesAuSiteParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://alphamosaik.com/'
        /// </summary>
        public string UIHowtoAssociateanAutoWindowUrl = "http://alphamosaik.com/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LIMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class LIMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'Conseiller les entreprises sur les solut' custom control's property 'TagName' equals 'LI'
        /// </summary>
        public string UIConseillerlesentreprCustomTagName = "LI";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRunningapplicationsWindow : WinWindow
    {
        
        public UIRunningapplicationsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Running applications";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public UIRunningapplicationsToolBar UIRunningapplicationsToolBar
        {
            get
            {
                if ((this.mUIRunningapplicationsToolBar == null))
                {
                    this.mUIRunningapplicationsToolBar = new UIRunningapplicationsToolBar(this);
                }
                return this.mUIRunningapplicationsToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIRunningapplicationsToolBar mUIRunningapplicationsToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRunningapplicationsToolBar : WinToolBar
    {
        
        public UIRunningapplicationsToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Running applications";
            this.WindowTitles.Add("Running applications");
            #endregion
        }
        
        #region Properties
        public WinControl UIInternetExplorerMenuButton
        {
            get
            {
                if ((this.mUIInternetExplorerMenuButton == null))
                {
                    this.mUIInternetExplorerMenuButton = new WinControl(this);
                    #region Search Criteria
                    this.mUIInternetExplorerMenuButton.SearchProperties[UITestControl.PropertyNames.Name] = "Internet Explorer";
                    this.mUIInternetExplorerMenuButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "MenuButton";
                    this.mUIInternetExplorerMenuButton.WindowTitles.Add("Running applications");
                    #endregion
                }
                return this.mUIInternetExplorerMenuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIInternetExplorerMenuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIJumpListWindow : WinWindow
    {
        
        public UIJumpListWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Jump List";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "9";
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public UIJumpListClient UIJumpListClient
        {
            get
            {
                if ((this.mUIJumpListClient == null))
                {
                    this.mUIJumpListClient = new UIJumpListClient(this);
                }
                return this.mUIJumpListClient;
            }
        }
        #endregion
        
        #region Fields
        private UIJumpListClient mUIJumpListClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIJumpListClient : WinClient
    {
        
        public UIJumpListClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Jump List");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIInternetExplorerMenuItem
        {
            get
            {
                if ((this.mUIInternetExplorerMenuItem == null))
                {
                    this.mUIInternetExplorerMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIInternetExplorerMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Internet Explorer";
                    this.mUIInternetExplorerMenuItem.WindowTitles.Add("Jump List");
                    #endregion
                }
                return this.mUIInternetExplorerMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIInternetExplorerMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleWindowsInterneWindow : BrowserWindow
    {
        
        public UIGoogleWindowsInterneWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Google";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("lpo - Recherche Google");
            this.WindowTitles.Add("leopold sedar senghor - Recherche Google");
            this.WindowTitles.Add("Léopold Sédar Senghor - Wikipédia");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        
        public UILéopoldSédarSenghorWDocument UILéopoldSédarSenghorWDocument
        {
            get
            {
                if ((this.mUILéopoldSédarSenghorWDocument == null))
                {
                    this.mUILéopoldSédarSenghorWDocument = new UILéopoldSédarSenghorWDocument(this);
                }
                return this.mUILéopoldSédarSenghorWDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleDocument mUIGoogleDocument;
        
        private UILéopoldSédarSenghorWDocument mUILéopoldSédarSenghorWDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.ca/";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("lpo - Recherche Google");
            this.WindowTitles.Add("leopold sedar senghor - Recherche Google");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIRechercherEdit
        {
            get
            {
                if ((this.mUIRechercherEdit == null))
                {
                    this.mUIRechercherEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIRechercherEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "lst-ib";
                    this.mUIRechercherEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Rechercher";
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "lst lst-tbb";
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=\"lst-ib\" class=\"lst lst-tbb\" title=\"R";
                    this.mUIRechercherEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIRechercherEdit.WindowTitles.Add("Google");
                    this.mUIRechercherEdit.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIRechercherEdit;
            }
        }
        
        public UIBodyPane UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public UIRsoCustom UIRsoCustom
        {
            get
            {
                if ((this.mUIRsoCustom == null))
                {
                    this.mUIRsoCustom = new UIRsoCustom(this);
                }
                return this.mUIRsoCustom;
            }
        }
        
        public UIRsoCustom1 UIRsoCustom1
        {
            get
            {
                if ((this.mUIRsoCustom1 == null))
                {
                    this.mUIRsoCustom1 = new UIRsoCustom1(this);
                }
                return this.mUIRsoCustom1;
            }
        }
        
        public UIRsoCustom3 UIRsoCustom3
        {
            get
            {
                if ((this.mUIRsoCustom3 == null))
                {
                    this.mUIRsoCustom3 = new UIRsoCustom3(this);
                }
                return this.mUIRsoCustom3;
            }
        }
        
        public UIRsoCustom4 UIRsoCustom4
        {
            get
            {
                if ((this.mUIRsoCustom4 == null))
                {
                    this.mUIRsoCustom4 = new UIRsoCustom4(this);
                }
                return this.mUIRsoCustom4;
            }
        }
        
        public UIRsoCustom7 UIRsoCustom7
        {
            get
            {
                if ((this.mUIRsoCustom7 == null))
                {
                    this.mUIRsoCustom7 = new UIRsoCustom7(this);
                }
                return this.mUIRsoCustom7;
            }
        }
        
        public UIRsoCustom9 UIRsoCustom9
        {
            get
            {
                if ((this.mUIRsoCustom9 == null))
                {
                    this.mUIRsoCustom9 = new UIRsoCustom9(this);
                }
                return this.mUIRsoCustom9;
            }
        }
        
        public UIRsoCustom10 UIRsoCustom10
        {
            get
            {
                if ((this.mUIRsoCustom10 == null))
                {
                    this.mUIRsoCustom10 = new UIRsoCustom10(this);
                }
                return this.mUIRsoCustom10;
            }
        }
        
        public UIRsoCustom11 UIRsoCustom11
        {
            get
            {
                if ((this.mUIRsoCustom11 == null))
                {
                    this.mUIRsoCustom11 = new UIRsoCustom11(this);
                }
                return this.mUIRsoCustom11;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIRechercherEdit;
        
        private UIBodyPane mUIBodyPane;
        
        private UIRsoCustom mUIRsoCustom;
        
        private UIRsoCustom1 mUIRsoCustom1;
        
        private UIRsoCustom3 mUIRsoCustom3;
        
        private UIRsoCustom4 mUIRsoCustom4;
        
        private UIRsoCustom7 mUIRsoCustom7;
        
        private UIRsoCustom9 mUIRsoCustom9;
        
        private UIRsoCustom10 mUIRsoCustom10;
        
        private UIRsoCustom11 mUIRsoCustom11;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIBodyPane : HtmlSpan
    {
        
        public UIBodyPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = ".pmoabs{position:absolute;right:0;top:32";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ctr-p";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\" class=\"ctr-p\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "40";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"height: 126px;\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "6";
                    this.mUIItemPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom : HtmlCustom
    {
        
        public UIRsoCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"VdpKTsLcE8rl0QHomLXsBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UILesPACcomlemeilleursPane
        {
            get
            {
                if ((this.mUILesPACcomlemeilleursPane == null))
                {
                    this.mUILesPACcomlemeilleursPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILesPACcomlemeilleursPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILesPACcomlemeilleursPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILesPACcomlemeilleursPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "LesPAC.com, le meilleur site d\'annonces ";
                    this.mUILesPACcomlemeilleursPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILesPACcomlemeilleursPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUILesPACcomlemeilleursPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUILesPACcomlemeilleursPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUILesPACcomlemeilleursPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUILesPACcomlemeilleursPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUILesPACcomlemeilleursPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom1 : HtmlCustom
    {
        
        public UIRsoCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"V9pKTq2NO-Xr0gHpx8DrBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UILightweightDirectoryPane
        {
            get
            {
                if ((this.mUILightweightDirectoryPane == null))
                {
                    this.mUILightweightDirectoryPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILightweightDirectoryPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILightweightDirectoryPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILightweightDirectoryPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Lightweight Directory Access Protocol (L";
                    this.mUILightweightDirectoryPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILightweightDirectoryPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUILightweightDirectoryPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUILightweightDirectoryPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUILightweightDirectoryPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUILightweightDirectoryPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUILightweightDirectoryPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom3 : HtmlCustom
    {
        
        public UIRsoCustom3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"XNpKTtGXCafq0gHdhIHrBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEncacheHyperlink
        {
            get
            {
                if ((this.mUIEncacheHyperlink == null))
                {
                    this.mUIEncacheHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "En cache";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/search";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://webcache.googleusercontent.com/search?q=cache:Awnrsg3PLA0J:www.lpo.fr/+lpo" +
                        "&cd=1&hl=fr&ct=clnk&gl=ca&source=www.google.ca";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "onmousedown=\"return rwt(this,\'\',\'\',\'\',\'1";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIEncacheHyperlink.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIEncacheHyperlink;
            }
        }
        
        public HtmlSpan UILaLPOagitauquotidienPane
        {
            get
            {
                if ((this.mUILaLPOagitauquotidienPane == null))
                {
                    this.mUILaLPOagitauquotidienPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILaLPOagitauquotidienPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILaLPOagitauquotidienPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILaLPOagitauquotidienPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "La LPO agit au quotidien depuis sa créat";
                    this.mUILaLPOagitauquotidienPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILaLPOagitauquotidienPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUILaLPOagitauquotidienPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUILaLPOagitauquotidienPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUILaLPOagitauquotidienPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUILaLPOagitauquotidienPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEncacheHyperlink;
        
        private HtmlSpan mUILaLPOagitauquotidienPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom4 : HtmlCustom
    {
        
        public UIRsoCustom4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"XNpKTs3sNYbs0gGLoKXrBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIEncachePane
        {
            get
            {
                if ((this.mUIEncachePane == null))
                {
                    this.mUIEncachePane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIEncachePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIEncachePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIEncachePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " - En cache";
                    this.mUIEncachePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIEncachePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "gl";
                    this.mUIEncachePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"gl\"";
                    this.mUIEncachePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
                    this.mUIEncachePane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIEncachePane;
            }
        }
        
        public HtmlDiv UIWww2poleemploifrInitPane
        {
            get
            {
                if ((this.mUIWww2poleemploifrInitPane == null))
                {
                    this.mUIWww2poleemploifrInitPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWww2poleemploifrInitPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWww2poleemploifrInitPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWww2poleemploifrInitPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "www2.pole-emploi.fr/.../InitialiserCrite";
                    this.mUIWww2poleemploifrInitPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWww2poleemploifrInitPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "f kv";
                    this.mUIWww2poleemploifrInitPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"f kv\"";
                    this.mUIWww2poleemploifrInitPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIWww2poleemploifrInitPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIWww2poleemploifrInitPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIEncachePane;
        
        private HtmlDiv mUIWww2poleemploifrInitPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom7 : HtmlCustom
    {
        
        public UIRsoCustom7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"Z9pKTtKrMY680AHvpI3rBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("lpo - Recherche Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIÉcoledelanguesLPSestPane
        {
            get
            {
                if ((this.mUIÉcoledelanguesLPSestPane == null))
                {
                    this.mUIÉcoledelanguesLPSestPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIÉcoledelanguesLPSestPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIÉcoledelanguesLPSestPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIÉcoledelanguesLPSestPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "École de langues LPS est une entreprise ";
                    this.mUIÉcoledelanguesLPSestPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIÉcoledelanguesLPSestPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUIÉcoledelanguesLPSestPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUIÉcoledelanguesLPSestPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIÉcoledelanguesLPSestPane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIÉcoledelanguesLPSestPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIÉcoledelanguesLPSestPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom9 : HtmlCustom
    {
        
        public UIRsoCustom9(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"b9pKTsDeDKHu0gHpqtjrBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("lpo - Recherche Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UILaboutiqueRéalisatioPane
        {
            get
            {
                if ((this.mUILaboutiqueRéalisatioPane == null))
                {
                    this.mUILaboutiqueRéalisatioPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILaboutiqueRéalisatioPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILaboutiqueRéalisatioPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILaboutiqueRéalisatioPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "La boutique - Réalisations - Carrières. ";
                    this.mUILaboutiqueRéalisatioPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILaboutiqueRéalisatioPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUILaboutiqueRéalisatioPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUILaboutiqueRéalisatioPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUILaboutiqueRéalisatioPane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUILaboutiqueRéalisatioPane;
            }
        }
        
        public HtmlDiv UIWwwleopoldbouchardcoPane
        {
            get
            {
                if ((this.mUIWwwleopoldbouchardcoPane == null))
                {
                    this.mUIWwwleopoldbouchardcoPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWwwleopoldbouchardcoPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWwwleopoldbouchardcoPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWwwleopoldbouchardcoPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "www.leopoldbouchard.com/ - En cachePages";
                    this.mUIWwwleopoldbouchardcoPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWwwleopoldbouchardcoPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "f kv";
                    this.mUIWwwleopoldbouchardcoPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"f kv\"";
                    this.mUIWwwleopoldbouchardcoPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIWwwleopoldbouchardcoPane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIWwwleopoldbouchardcoPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUILaboutiqueRéalisatioPane;
        
        private HtmlDiv mUIWwwleopoldbouchardcoPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom10 : HtmlCustom
    {
        
        public UIRsoCustom10(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"ctpKTuKOFOTW0QHw6rjsBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("lpo - Recherche Google");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIFrwikipediaorgwikiLéPane
        {
            get
            {
                if ((this.mUIFrwikipediaorgwikiLéPane == null))
                {
                    this.mUIFrwikipediaorgwikiLéPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIFrwikipediaorgwikiLéPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIFrwikipediaorgwikiLéPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "fr.wikipedia.org/wiki/Léopold_Simoneau -";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "f kv";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"f kv\"";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIFrwikipediaorgwikiLéPane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIFrwikipediaorgwikiLéPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIFrwikipediaorgwikiLéPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIRsoCustom11 : HtmlCustom
    {
        
        public UIRsoCustom11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "OL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"d9pKTuuwIefY0QH72eTrBw\"";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("lpo - Recherche Google");
            this.WindowTitles.Add("leopold sedar senghor - Recherche Google");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UILéopoldSédarSenghorePane
        {
            get
            {
                if ((this.mUILéopoldSédarSenghorePane == null))
                {
                    this.mUILéopoldSédarSenghorePane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILéopoldSédarSenghorePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILéopoldSédarSenghorePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILéopoldSédarSenghorePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Léopold Sédar Senghor est un poète, écri";
                    this.mUILéopoldSédarSenghorePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILéopoldSédarSenghorePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUILéopoldSédarSenghorePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUILéopoldSédarSenghorePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUILéopoldSédarSenghorePane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUILéopoldSédarSenghorePane;
            }
        }
        
        public HtmlDiv UIFrwikipediaorgwikiLéPane
        {
            get
            {
                if ((this.mUIFrwikipediaorgwikiLéPane == null))
                {
                    this.mUIFrwikipediaorgwikiLéPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIFrwikipediaorgwikiLéPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIFrwikipediaorgwikiLéPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "fr.wikipedia.org/wiki/Léopold_Sédar_Seng";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "s";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"s\"";
                    this.mUIFrwikipediaorgwikiLéPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
                    this.mUIFrwikipediaorgwikiLéPane.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIFrwikipediaorgwikiLéPane;
            }
        }
        
        public HtmlHyperlink UIEncacheHyperlink
        {
            get
            {
                if ((this.mUIEncacheHyperlink == null))
                {
                    this.mUIEncacheHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEncacheHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "En cache";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/search";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://webcache.googleusercontent.com/search?q=cache:SxJqqF2KfRMJ:fr.wikipedia.or" +
                        "g/wiki/L%C3%A9opold_S%C3%A9dar_Senghor+leopold+sedar+senghor&cd=1&hl=fr&ct=clnk&" +
                        "gl=ca&source=www.google.ca";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "onmousedown=\"return rwt(this,\'\',\'\',\'\',\'1";
                    this.mUIEncacheHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIEncacheHyperlink.WindowTitles.Add("lpo - Recherche Google");
                    #endregion
                }
                return this.mUIEncacheHyperlink;
            }
        }
        
        public HtmlHyperlink UILéopoldSédarSenghorWHyperlink
        {
            get
            {
                if ((this.mUILéopoldSédarSenghorWHyperlink == null))
                {
                    this.mUILéopoldSédarSenghorWHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILéopoldSédarSenghorWHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILéopoldSédarSenghorWHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILéopoldSédarSenghorWHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILéopoldSédarSenghorWHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Léopold Sédar Senghor - Wikipédia";
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/wiki/L%C3%A9opold_S%C3%A9dar_Senghor";
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://fr.wikipedia.org/wiki/L%C3%A9opold_S%C3%A9dar_Senghor";
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "l";
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"l\" onmousedown=\"return rwt(this,\'";
                    this.mUILéopoldSédarSenghorWHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUILéopoldSédarSenghorWHyperlink.WindowTitles.Add("leopold sedar senghor - Recherche Google");
                    #endregion
                }
                return this.mUILéopoldSédarSenghorWHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUILéopoldSédarSenghorePane;
        
        private HtmlDiv mUIFrwikipediaorgwikiLéPane;
        
        private HtmlHyperlink mUIEncacheHyperlink;
        
        private HtmlHyperlink mUILéopoldSédarSenghorWHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UILéopoldSédarSenghorWDocument : HtmlDocument
    {
        
        public UILéopoldSédarSenghorWDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Léopold Sédar Senghor - Wikipédia";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/wiki/L%C3%A9opold_S%C3%A9dar_Senghor";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://fr.wikipedia.org/wiki/L%C3%A9opold_S%C3%A9dar_Senghor";
            this.WindowTitles.Add("Léopold Sédar Senghor - Wikipédia");
            #endregion
        }
        
        #region Properties
        public HtmlTable UITocTable
        {
            get
            {
                if ((this.mUITocTable == null))
                {
                    this.mUITocTable = new HtmlTable(this);
                    #region Search Criteria
                    this.mUITocTable.SearchProperties[HtmlTable.PropertyNames.Id] = "toc";
                    this.mUITocTable.SearchProperties[HtmlTable.PropertyNames.Name] = null;
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.InnerText] = "\r\n\r\n\r\n\r\nSommaire\r\n [masquer] 1 Biographi";
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=\"toc\" class=\"toc\"";
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.Class] = "toc";
                    this.mUITocTable.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
                    this.mUITocTable.WindowTitles.Add("Léopold Sédar Senghor - Wikipédia");
                    #endregion
                }
                return this.mUITocTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlTable mUITocTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHowtoAssociateanAutoWindow : BrowserWindow
    {
        
        public UIHowtoAssociateanAutoWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "How to: Associate an Automated Test with a Test Case";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("How to: Associate an Automated Test with a Test Case");
            this.WindowTitles.Add("New Tab");
            this.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                    "ommunication, ");
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Home");
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                    "t Sécurité");
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Applications - Home");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UITabRowTabList UITabRowTabList
        {
            get
            {
                if ((this.mUITabRowTabList == null))
                {
                    this.mUITabRowTabList = new UITabRowTabList(this);
                }
                return this.mUITabRowTabList;
            }
        }
        
        public UIAlphaMosaïkMontréalQDocument UIAlphaMosaïkMontréalQDocument
        {
            get
            {
                if ((this.mUIAlphaMosaïkMontréalQDocument == null))
                {
                    this.mUIAlphaMosaïkMontréalQDocument = new UIAlphaMosaïkMontréalQDocument(this);
                }
                return this.mUIAlphaMosaïkMontréalQDocument;
            }
        }
        
        public UIAlphaMosaïkMontréalSDocument UIAlphaMosaïkMontréalSDocument
        {
            get
            {
                if ((this.mUIAlphaMosaïkMontréalSDocument == null))
                {
                    this.mUIAlphaMosaïkMontréalSDocument = new UIAlphaMosaïkMontréalSDocument(this);
                }
                return this.mUIAlphaMosaïkMontréalSDocument;
            }
        }
        
        public UIAlphaMosaïkMontréalSDocument1 UIAlphaMosaïkMontréalSDocument1
        {
            get
            {
                if ((this.mUIAlphaMosaïkMontréalSDocument1 == null))
                {
                    this.mUIAlphaMosaïkMontréalSDocument1 = new UIAlphaMosaïkMontréalSDocument1(this);
                }
                return this.mUIAlphaMosaïkMontréalSDocument1;
            }
        }
        
        public UIAlphaMosaïkMontréalSDocument11 UIAlphaMosaïkMontréalSDocument11
        {
            get
            {
                if ((this.mUIAlphaMosaïkMontréalSDocument11 == null))
                {
                    this.mUIAlphaMosaïkMontréalSDocument11 = new UIAlphaMosaïkMontréalSDocument11(this);
                }
                return this.mUIAlphaMosaïkMontréalSDocument11;
            }
        }
        #endregion
        
        #region Fields
        private UITabRowTabList mUITabRowTabList;
        
        private UIAlphaMosaïkMontréalQDocument mUIAlphaMosaïkMontréalQDocument;
        
        private UIAlphaMosaïkMontréalSDocument mUIAlphaMosaïkMontréalSDocument;
        
        private UIAlphaMosaïkMontréalSDocument1 mUIAlphaMosaïkMontréalSDocument1;
        
        private UIAlphaMosaïkMontréalSDocument11 mUIAlphaMosaïkMontréalSDocument11;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITabRowTabList : WinTabList
    {
        
        public UITabRowTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabList.PropertyNames.Name] = "Tab Row";
            this.WindowTitles.Add("How to: Associate an Automated Test with a Test Case");
            #endregion
        }
        
        #region Properties
        public WinButton UINewTabCtrlTButton
        {
            get
            {
                if ((this.mUINewTabCtrlTButton == null))
                {
                    this.mUINewTabCtrlTButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINewTabCtrlTButton.SearchProperties[WinButton.PropertyNames.Name] = "New Tab (Ctrl+T)";
                    this.mUINewTabCtrlTButton.WindowTitles.Add("How to: Associate an Automated Test with a Test Case");
                    #endregion
                }
                return this.mUINewTabCtrlTButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINewTabCtrlTButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAlphaMosaïkMontréalQDocument : HtmlDocument
    {
        
        public UIAlphaMosaïkMontréalQDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                "ommunication, gestion de projets et processus d\'affaires";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/pages/accueil.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.alphamosaik.com/pages/accueil.aspx";
            this.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                    "ommunication, ");
            #endregion
        }
        
        #region Properties
        public UIPlacementCell UIPlacementCell
        {
            get
            {
                if ((this.mUIPlacementCell == null))
                {
                    this.mUIPlacementCell = new UIPlacementCell(this);
                }
                return this.mUIPlacementCell;
            }
        }
        
        public UIInfraTechnoCell UIInfraTechnoCell
        {
            get
            {
                if ((this.mUIInfraTechnoCell == null))
                {
                    this.mUIInfraTechnoCell = new UIInfraTechnoCell(this);
                }
                return this.mUIInfraTechnoCell;
            }
        }
        #endregion
        
        #region Fields
        private UIPlacementCell mUIPlacementCell;
        
        private UIInfraTechnoCell mUIInfraTechnoCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIPlacementCell : HtmlCell
    {
        
        public UIPlacementCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlCell.PropertyNames.Id] = "Placement";
            this.SearchProperties[HtmlCell.PropertyNames.Name] = null;
            this.FilterProperties[HtmlCell.PropertyNames.InnerText] = " ";
            this.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "id=Placement";
            this.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
            this.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "3";
            this.FilterProperties[HtmlCell.PropertyNames.Class] = null;
            this.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "21";
            this.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                    "ommunication, ");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = " ";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = null;
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                    "ommunication, ");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.InnerText] = " ";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIItemCell.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                            "ommunication, ");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIInfraTechnoCell : HtmlCell
    {
        
        public UIInfraTechnoCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlCell.PropertyNames.Id] = "InfraTechno";
            this.SearchProperties[HtmlCell.PropertyNames.Name] = null;
            this.FilterProperties[HtmlCell.PropertyNames.InnerText] = " ";
            this.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "id=InfraTechno";
            this.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
            this.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
            this.FilterProperties[HtmlCell.PropertyNames.Class] = null;
            this.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "19";
            this.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                    "ommunication, ");
            #endregion
        }
        
        #region Properties
        public HtmlImage UISolutions1InfrastrucImage
        {
            get
            {
                if ((this.mUISolutions1InfrastrucImage == null))
                {
                    this.mUISolutions1InfrastrucImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUISolutions1InfrastrucImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUISolutions1InfrastrucImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUISolutions1InfrastrucImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Solutions1/InfrastructureTechnologique.png";
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://www.alphamosaik.com/Solutions1/InfrastructureTechnologique.png";
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Solutions/InfrastructureTechnologique";
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://www.alphamosaik.com/Solutions/InfrastructureTechnologique";
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "style=\"BORDER-RIGHT-WIDTH: 0px; BORDER-T";
                    this.mUISolutions1InfrastrucImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUISolutions1InfrastrucImage.WindowTitles.Add("AlphaMosaïk Montréal(Québec) Canada: SharePoint, Infrastructure, sécurité & téléc" +
                            "ommunication, ");
                    #endregion
                }
                return this.mUISolutions1InfrastrucImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUISolutions1InfrastrucImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAlphaMosaïkMontréalSDocument : HtmlDocument
    {
        
        public UIAlphaMosaïkMontréalSDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Home";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Solutions/InfrastructureTechnologique/Pages/default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.alphamosaik.com/Solutions/InfrastructureTechnologique/Pages/default.as" +
                "px";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Home");
            #endregion
        }
        
        #region Properties
        public UICtl00_PlaceHolderAlpPane UICtl00_PlaceHolderAlpPane
        {
            get
            {
                if ((this.mUICtl00_PlaceHolderAlpPane == null))
                {
                    this.mUICtl00_PlaceHolderAlpPane = new UICtl00_PlaceHolderAlpPane(this);
                }
                return this.mUICtl00_PlaceHolderAlpPane;
            }
        }
        #endregion
        
        #region Fields
        private UICtl00_PlaceHolderAlpPane mUICtl00_PlaceHolderAlpPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICtl00_PlaceHolderAlpPane : HtmlDiv
    {
        
        public UICtl00_PlaceHolderAlpPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_PlaceHolderAlphaMosaikContent_RichHtmlField1__ControlWrapper_RichHtmlField";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "AlphaMosaik vous propose les options sui";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-rtestate-field";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"DISPLAY: inline\" id=ctl00_PlaceHo";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "73";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Home");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIInfrastructureetSécuHyperlink
        {
            get
            {
                if ((this.mUIInfrastructureetSécuHyperlink == null))
                {
                    this.mUIInfrastructureetSécuHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIInfrastructureetSécuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIInfrastructureetSécuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIInfrastructureetSécuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIInfrastructureetSécuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Infrastructure et Sécurité";
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Solutions/InfrastructureTechnologique/Pages/Infrastructure-et-securite.aspx";
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.alphamosaik.com/Solutions/InfrastructureTechnologique/Pages/Infrastruc" +
                        "ture-et-securite.aspx";
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Solutions/InfrastructureTechnolog";
                    this.mUIInfrastructureetSécuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIInfrastructureetSécuHyperlink.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Home");
                    #endregion
                }
                return this.mUIInfrastructureetSécuHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIInfrastructureetSécuHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAlphaMosaïkMontréalSDocument1 : HtmlDocument
    {
        
        public UIAlphaMosaïkMontréalSDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                "t Sécurité";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Solutions/InfrastructureTechnologique/Pages/Infrastructure-et-securite.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.alphamosaik.com/Solutions/InfrastructureTechnologique/Pages/Infrastruc" +
                "ture-et-securite.aspx";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                    "t Sécurité");
            #endregion
        }
        
        #region Properties
        public UICtl00_PlaceHolderAlpPane1 UICtl00_PlaceHolderAlpPane
        {
            get
            {
                if ((this.mUICtl00_PlaceHolderAlpPane == null))
                {
                    this.mUICtl00_PlaceHolderAlpPane = new UICtl00_PlaceHolderAlpPane1(this);
                }
                return this.mUICtl00_PlaceHolderAlpPane;
            }
        }
        
        public UIZz2_CurrentNavPane UIZz2_CurrentNavPane
        {
            get
            {
                if ((this.mUIZz2_CurrentNavPane == null))
                {
                    this.mUIZz2_CurrentNavPane = new UIZz2_CurrentNavPane(this);
                }
                return this.mUIZz2_CurrentNavPane;
            }
        }
        #endregion
        
        #region Fields
        private UICtl00_PlaceHolderAlpPane1 mUICtl00_PlaceHolderAlpPane;
        
        private UIZz2_CurrentNavPane mUIZz2_CurrentNavPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICtl00_PlaceHolderAlpPane1 : HtmlDiv
    {
        
        public UICtl00_PlaceHolderAlpPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_PlaceHolderAlphaMosaikContent_ctl02__ControlWrapper_RichHtmlField";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Analyser les besoins en infrastructure d";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-rtestate-field";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"DISPLAY: inline\" id=ctl00_PlaceHo";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "73";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                    "t Sécurité");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIConseillerlesentreprCustom
        {
            get
            {
                if ((this.mUIConseillerlesentreprCustom == null))
                {
                    this.mUIConseillerlesentreprCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIConseillerlesentreprCustom.SearchProperties["Id"] = null;
                    this.mUIConseillerlesentreprCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIConseillerlesentreprCustom.SearchProperties["TagName"] = "LI";
                    this.mUIConseillerlesentreprCustom.FilterProperties["Class"] = null;
                    this.mUIConseillerlesentreprCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIConseillerlesentreprCustom.FilterProperties["InnerText"] = "Conseiller les entreprises sur les solut";
                    this.mUIConseillerlesentreprCustom.FilterProperties["TagInstance"] = "4";
                    this.mUIConseillerlesentreprCustom.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                            "t Sécurité");
                    #endregion
                }
                return this.mUIConseillerlesentreprCustom;
            }
        }
        
        public HtmlCustom UIAnalyserlesbesoinsenCustom
        {
            get
            {
                if ((this.mUIAnalyserlesbesoinsenCustom == null))
                {
                    this.mUIAnalyserlesbesoinsenCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIAnalyserlesbesoinsenCustom.SearchProperties["Id"] = null;
                    this.mUIAnalyserlesbesoinsenCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIAnalyserlesbesoinsenCustom.SearchProperties["TagName"] = "LI";
                    this.mUIAnalyserlesbesoinsenCustom.FilterProperties["Class"] = null;
                    this.mUIAnalyserlesbesoinsenCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIAnalyserlesbesoinsenCustom.FilterProperties["InnerText"] = "Analyser les besoins en infrastructure d";
                    this.mUIAnalyserlesbesoinsenCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIAnalyserlesbesoinsenCustom.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                            "t Sécurité");
                    #endregion
                }
                return this.mUIAnalyserlesbesoinsenCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIConseillerlesentreprCustom;
        
        private HtmlCustom mUIAnalyserlesbesoinsenCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIZz2_CurrentNavPane : HtmlDiv
    {
        
        public UIZz2_CurrentNavPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "zz2_CurrentNav";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "ApplicationsSolutions Hébergées Microsof";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=zz2_CurrentNav";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "76";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                    "t Sécurité");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIApplicationsHyperlink
        {
            get
            {
                if ((this.mUIApplicationsHyperlink == null))
                {
                    this.mUIApplicationsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIApplicationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIApplicationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIApplicationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIApplicationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Applications";
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Solutions/Applications/Pages/default.aspx";
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.alphamosaik.com/Solutions/Applications/Pages/default.aspx";
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "static menu-item";
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"static menu-item\" href=\"/Solution";
                    this.mUIApplicationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIApplicationsHyperlink.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Technological Infrastructure - Infrastructure e" +
                            "t Sécurité");
                    #endregion
                }
                return this.mUIApplicationsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIApplicationsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAlphaMosaïkMontréalSDocument11 : HtmlDocument
    {
        
        public UIAlphaMosaïkMontréalSDocument11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AlphaMosaïk Montréal - Solutions: Applications - Home";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Solutions/Applications/Pages/default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.alphamosaik.com/Solutions/Applications/Pages/default.aspx";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Applications - Home");
            #endregion
        }
        
        #region Properties
        public UICtl00_PlaceHolderAlpPane2 UICtl00_PlaceHolderAlpPane
        {
            get
            {
                if ((this.mUICtl00_PlaceHolderAlpPane == null))
                {
                    this.mUICtl00_PlaceHolderAlpPane = new UICtl00_PlaceHolderAlpPane2(this);
                }
                return this.mUICtl00_PlaceHolderAlpPane;
            }
        }
        #endregion
        
        #region Fields
        private UICtl00_PlaceHolderAlpPane2 mUICtl00_PlaceHolderAlpPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICtl00_PlaceHolderAlpPane2 : HtmlDiv
    {
        
        public UICtl00_PlaceHolderAlpPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_PlaceHolderAlphaMosaikContent_RichHtmlField1__ControlWrapper_RichHtmlField";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "AlphaMosaik vous propose les application";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-rtestate-field";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"DISPLAY: inline\" id=ctl00_PlaceHo";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "73";
            this.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Applications - Home");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIModuleMultilingueHyperlink
        {
            get
            {
                if ((this.mUIModuleMultilingueHyperlink == null))
                {
                    this.mUIModuleMultilingueHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIModuleMultilingueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIModuleMultilingueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIModuleMultilingueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIModuleMultilingueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Module Multilingue";
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Solutions/Applications/Pages/Module-Multilingue.aspx";
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Module Multilingue";
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.alphamosaik.com/Solutions/Applications/Pages/Module-Multilingue.aspx";
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"\" href=\"/Solutions/Applications/P";
                    this.mUIModuleMultilingueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIModuleMultilingueHyperlink.WindowTitles.Add("AlphaMosaïk Montréal - Solutions: Applications - Home");
                    #endregion
                }
                return this.mUIModuleMultilingueHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIModuleMultilingueHyperlink;
        #endregion
    }
}
